services:

  webapp:
    build: ./webapp
    ports:
      - "8080:80"
    depends_on:
      - api
      - auth

  api:
    build: ./api
    depends_on:
      - db
      - internal

  auth:
    build: ./auth
    depends_on:
      - db

  internal:
    build: ./internal

  logs:
    build: ./logs

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: