services:

  webapp:
    build: ./webapp
    ports:
      - "8080:80"

  api:
    build: ./api
    ports:
      - "5000:5000"

  auth:
    build: ./auth
    ports:
      - "5001:5001"

  internal:
    build: ./internal

  logs:
    build: ./logs
    ports:
      - "5003:5003"

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: