events {}

http {
    server {
        listen 80;

        location / {

            # Basic WAF rules
            if ($args ~* "(\.\./|/etc/passwd|127\.0\.0\.1|localhost)") {
                return 403;
            }

            if ($args ~* "(union|select|sleep|benchmark|drop|insert)") {
                return 403;
            }

            proxy_pass http://webapp:80;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}