events {}

http {

    log_format custom_logs '$remote_addr - $time_local '
                           '"$request" $status '
                           '"$http_user_agent" '
                           'ARGS="$args"';

    access_log /var/log/nginx/access.log custom_logs;
    error_log /var/log/nginx/error.log;

    server {
        listen 80;

        location / {

            # SSRF block
            if ($args ~* "(localhost|127\.0\.0\.1|internal|169\.254\.169\.254)") {
                return 403;
            }

            # SQLi block
            if ($args ~* "(union|select|sleep|benchmark|drop|insert)") {
                return 403;
            }

            proxy_pass http://webapp:80;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}